<a href="https://colab.research.google.com/github/Soviet117/lima-rent-predictive/blob/main/notebooks/01_ETL_PySpark.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# PASO 1: Montar Google Drive
from google.colab import drive
drive.mount('/content/drive')

# PASO 2: Verificar que el archivo existe
import os
file_path = '/content/drive/MyDrive/lima_rent/dataset.csv'
if os.path.exists(file_path):
    print("Archivo encontrado en:", file_path)
else:
    print("Archivo NO encontrado. Verifica la ruta.")

Mounted at /content/drive
Archivo encontrado en: /content/drive/MyDrive/lima_rent/dataset.csv

In [3]:
import pandas as pd

df = pd.read_csv(file_path)
print(f"Dimensiones: {df.shape}")
print("\nPrimeras 5 filas:")
df.head()

Dimensiones: (1079, 12)

Primeras 5 filas:

,title,location,price,bedroom,bathroom,area,year_contruction,maintenance,housing_type,operation_type,date_pub,url
0,Apartamento en alquiler en Ur. Santa Cruz,"Ur. Santa Cruz, Miraflores, Lima, Lima",USD900,2 dormitorios,2 baños,103 m²,2010,NaN,Apartamento,Alquiler,"Hace 1 semana, 1 día - Publicado por GARRIDO S...",https://www.properati.com.pe/detalle/14032-32-...
1,Apartamento en alquiler en Cercado,"Cercado, Arequipa, Arequipa, Arequipa","S/.3,100",3 dormitorios,4 baños,151 m²,2021,NaN,Apartamento,Alquiler,7 feb. 2023 - Publicado por Inmuebles Peruanos,https://www.properati.com.pe/detalle/14032-32-...
2,Apartamento en alquiler en Ur. San Luis,"Ur. San Luis, Barranco, Lima, Lima",USD720,2 dormitorios,2 baños,66 m²,2020,S/.150,Apartamento,Alquiler,26 mar. 2023 - Publicado por JESUS ALTAMIRANO ...,https://www.properati.com.pe/detalle/14032-32-...
3,Apartamento en alquiler en Ur. Risso,"Ur. Risso, Lince, Lima, Lima","S/.2,600",1 dormitorio,2 baños,60 m²,NaN,S/.330,Apartamento,Alquiler,"Hace 1 día, 18 horas - Publicado por KRB Agenc...",https://www.properati.com.pe/detalle/14032-32-...
4,Apartamento en alquiler en Ur. Chacarilla Del ...,"Ur. Chacarilla Del Estanque, Santiago de Surco...","S/.2,300",2 dormitorios,2 baños,50 m²,2022,S/.250,Apartamento,Alquiler,"Hace 2 semanas, 3 días - Publicado por CASA VI...",https://www.properati.com.pe/detalle/14032-32-...

In [4]:
# Ver tipos de datos y nulos
print("\nInformación del dataset:")
df.info()

print("\nEstadísticas descriptivas:")
df.describe()

print("\nValores nulos por columna:")
df.isnull().sum()

Información del dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1079 entries, 0 to 1078
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title             1079 non-null   object
 1   location          1079 non-null   object
 2   price             1079 non-null   object
 3   bedroom           1079 non-null   object
 4   bathroom          1079 non-null   object
 5   area              1046 non-null   object
 6   year_contruction  837 non-null    object
 7   maintenance       631 non-null    object
 8   housing_type      1079 non-null   object
 9   operation_type    1079 non-null   object
 10  date_pub          1079 non-null   object
 11  url               1079 non-null   object
dtypes: object(12)
memory usage: 101.3+ KB

Estadísticas descriptivas:

Valores nulos por columna:

title                 0
location              0
price                 0
bedroom               0
bathroom              0
area                 33
year_contruction    242
maintenance         448
housing_type          0
operation_type        0
date_pub              0
url                   0
dtype: int64